controller_list:
  - name: arm_controller
    ns: follow_joint_trajectory
    default: true
    joints:
      - arm_lift_joint
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_upperarm_roll_joint
      - arm_elbow_flex_joint
      - arm_forearm_roll_joint
      - arm_wrist_flex_joint
      - arm_wrist_roll_joint
  - name: gripper_controller
    default: true
    joints:
      - l_gripper_joint
      - r_gripper_joint
