sensors:
  - sensor_type: depth_image_sensor
    image_topic: /camera/depth_registered/image_raw
    queue_size: 5
    near_clipping_plane_distance: 0.3
    far_clipping_plane_distance: 5.0
    shadow_threshold: 0.5
    padding_scale: 2.0
    padding_offset: 0.01
